modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/YukkuriC/${mod_name}/issues"
license = "MIT"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${mod_name}"
authors = "YukkuriC"
description = '''
Provide items with ability listening to various game events and triggering custom spells.
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/${modid}/forge_updates.json"
displayURL = "https://modrinth.com/mod/${modid}"

[[dependencies.${modid}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},${mc_version}.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "hexcasting"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
